<a href="https://colab.research.google.com/github/joaoleal02/Ambev_iHops/blob/master/ambev_1_semifinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [287]:
import pandas as pd
import datetime
empdata = pd.read_csv(r'tabela_ambev_sql_finale.csv',index_col=False, delimiter=';')
empdata['Doc. Date'] = pd.to_datetime(empdata['Doc. Date'], format='%d/%m/%Y')
dados = empdata.loc[empdata['Postal Code'] == 83630]
print(dados)

       Doc. Date  Order qty  ...   Pre√ßo/L  Container Size 2
10    2021-01-11       70.0  ...  2.629129               6.0
11    2021-01-11      140.0  ...  3.775200               6.0
12    2021-01-11      210.0  ...  3.666000               6.0
13    2021-01-11       70.0  ...  3.015600               6.0
14    2021-01-11       70.0  ...  3.733615               6.0
...          ...        ...  ...       ...               ...
21180 2019-12-11       70.0  ...  3.775200               6.0
21181 2019-12-11       70.0  ...  2.629129               6.0
21182 2019-12-11      420.0  ...  2.923183               6.0
21183 2019-12-11      140.0  ...  3.666000               6.0
21184 2019-12-11       70.0  ...  3.015600               6.0

[502 rows x 16 columns]

In [288]:
beer_user = dados.iloc[0]['Subrand']
print(beer_user)

BUD

In [289]:
from sklearn.cluster import KMeans
import numpy as np

#importando base de dados
df = pd.read_csv("MLiHops.csv")
df

                subrand   ibu  abv (%)  corpo  aroma  tipo
0       BIRRA DEL BORGO  20.0      5.0      1      0    40
1                   BUD  10.0      5.0      0      0     2
2          CAMDEN HELLS  29.0      4.6      0      0     2
3       CAMDEN PALE ALE  39.0      4.0      1      5    40
4          CORONA EXTRA  18.0      4.6      0      0     2
5       GINETTE BLANCHE  12.0      5.0      0      0    41
6        GINETTE BLONDE  29.0      5.0      2      0    40
7         GINETTE FRUIT  12.0      4.0      1      5    20
8         GINETTE LAGER  25.0      4.5      0      0     2
9        GINETTE TRIPLE  15.0      9.0      1     10    44
10                GOOSE  55.0      5.9      1      5    45
11  HOEGARDEN GRAND CRU  35.0      8.5      1      5    46
12       HOEGARDEN ROSE   5.0      3.0      2      5    20
13      HOEGARDEN WHITE  15.0      4.9      0      5    41
14                 KWAK  16.0      8.4      2      5    46
15         LEFFE AMBREE  25.0      6.6      1     15    40
16        LEFFE BLONDE   21.5      6.6      0     15    42
17     LEFFE BLONDE 0,0  10.0      0.0      0     10    42
18          LEFFE BRUNE  20.0      6.5      0     15    43
19      LEFFE LA LEGERE  17.0      5.0      0     15     2
20       LEFFE RITUEL 9  25.0      9.0      2     15    46
21         LEFFE ROYALE  33.0      7.5      1      5    42
22           LEFFE RUBY  10.0      5.0      0      5    20
23         LEFFE TRIPLE  15.0      8.5      1      5    44
24     TRIPLE KARMELIET  31.0      8.4      1     15    44

In [290]:
array1 = []

dicRecomendacao = {

  "Harmonizacao": {
  40 : "AMERICAN PALE ALE - Carnes grelhadas e saladas c√≠tricas",
  2: "PALE LAGER - Hamburger, carnes vermelha e petiscos",
  43: "BROWN ALE - Carnes e petiscos",
  41: "WITBIER - Saladas, frutas do mar e comidas leves",
  44: "TRIPEL - Massas e frutos do mar",
  42: "BLONDE - Petiscos e frutos do mar",
  45: "STRONG - Frutos do mar e massas",
  46: "INDIAN PALE ALE - Queijo, carne vermelha, hamburger e petiscos",
  20: "FRUIT BEER - Sobremesa",
  },
  "Temperatura": {
  40: [8, 12],
  2: [0, 4],
  43: [8, 12],
  41: [4, 7],
  44: [4, 7],
  42: [2, 5],
  45: [10, 12],
  46: [8, 12],
  20: [7, 10],
  }
}

for i in range(25):  #itera sobre os valores e adiciona na lista array1

    temp = []
    temp.clear()

    p1 = df.iloc[i]['ibu']
    temp.append(p1)
    p2 = df.iloc[i]['abv (%)']
    temp.append(p2)
    p3 = df.iloc[i]['corpo']
    temp.append(p3)
    p4 = df.iloc[i]['aroma']
    temp.append(p4)
    p5 = df.iloc[i]['tipo']
    temp.append(p5)
    #p6 = dp.iloc[]["preco"]
    #temp.append(p6)

    array1.append(temp)

X = np.array(array1) #transforma a lista array1 em numpy

print(array1)

[[20.0, 5.0, 1, 0, 40], [10.0, 5.0, 0, 0, 2], [29.0, 4.6, 0, 0, 2], [39.0, 4.0, 1, 5, 40], [18.0, 4.6, 0, 0, 2], [12.0, 5.0, 0, 0, 41], [29.0, 5.0, 2, 0, 40], [12.0, 4.0, 1, 5, 20], [25.0, 4.5, 0, 0, 2], [15.0, 9.0, 1, 10, 44], [55.0, 5.9, 1, 5, 45], [35.0, 8.5, 1, 5, 46], [5.0, 3.0, 2, 5, 20], [15.0, 4.9, 0, 5, 41], [16.0, 8.4, 2, 5, 46], [25.0, 6.6, 1, 15, 40], [21.5, 6.6, 0, 15, 42], [10.0, 0.0, 0, 10, 42], [20.0, 6.5, 0, 15, 43], [17.0, 5.0, 0, 15, 2], [25.0, 9.0, 2, 15, 46], [33.0, 7.5, 1, 5, 42], [10.0, 5.0, 0, 5, 20], [15.0, 8.5, 1, 5, 44], [31.0, 8.4, 1, 15, 44]]

In [291]:
kmeans = KMeans(n_clusters=9, random_state=0).fit(X)
#pega todas a variaveis e as coloca em 10 grupos (mais parecidas)
tips = kmeans.labels_
print(tips)

[4 7 1 8 7 4 8 3 1 0 5 8 3 4 4 2 2 0 2 6 2 8 3 4 2]

In [303]:
def busca(array,beer):
    for i,el in enumerate(array):
        if el==beer:
            return i
    return None
################################################################################
def sum_array(array):
  soma = 0
  for i in array:
    soma += i
  return(soma/len(array))


def DataPreco(data, cerveja):
  mes = data[3:5]
  ano = data[6:]
  dia = data[:2]
  mes_atual = mes
  ano_atual = str(int(ano) - 1)
  dia_atual = dia
  dia30 = [4, 6, 9, 11]

  filtered_df = empdata.loc[(empdata['Doc. Date'] >= f'{dia_atual}/{mes_atual}/{ano_atual}') & (empdata['Doc. Date'] < f'{dia_atual}/{mes_atual}/{ano}')]
  filtered_df = filtered_df.loc[filtered_df["Subrand"] == cerveja]
  filtered_df.sort_values(by=['Doc. Date'], inplace = True, ascending = False)
  print(filtered_df.head())
  data_array = filtered_df['Pre√ßo/L'].to_numpy()
  media = sum_array(data_array)
  print(media)
  # preco_medio = 0

  # for i in range(len(cerva_df)):
  #   preco_medio += cerva_df.iloc[i]['Pre√ßo/L']

  # print(preco_medio)

  # while preco_medio == 0:
  #   novo_mes = int(mes)
  #   novo_ano = int(ano)
  #   if novo_mes != 1:
  #     novo_mes = novo_mes -1
  #   else:
  #     novo_mes = 12
  #     novo_ano = novo_ano - 1

  #   if novo_mes == 2:
  #     novo_dia = 28
  #   elif novo_mes in dia30:
  #     novo_dia = 30
  #   else:
  #     novo_dia = 31

  #   ano = str(novo_ano)
  #   mes = str(novo_mes)
  #   dia = str(novo_dia)

  #   filtered_df = empdata.loc[(empdata['Doc. Date'] >= f'01/{mes}/{ano}') & (empdata['Doc. Date'] < f'{dia}/{mes}/{ano}')]
  #   cerva_df = filtered_df.loc[filtered_df["Subrand"] == cerveja]
  #   cerva_df.sort_values(by=['Doc. Date'], inplace = True, ascending = False)
  #   print(cerva_df)

  return
################################################################################
beer_array = df['subrand'].to_numpy()
tipo_array = df["tipo"].to_numpy()
Y = busca(beer_array, beer_user)
#print(Y)
qlqr = array1[Y]
a = kmeans.predict([qlqr])
#print(a)
var = np.where(tips == a)
print("\n")
#saida da cerveja
bc = ""
cerveja_escolhida = []
print_out = ""
saida = False
dia_atual = "31/01/2021"
#Ultimo dia da tabela

for i in (var):
  for ele in range(len(i)):
    bc = beer_array[i[ele]]
    var_a = i
    var_b = ele
    if bc != beer_user:
      saida = True
      cerveja_escolhida.append(bc)
      ad = i[ele]
      tipo_real = tipo_array[ad]
      #print(tipo_real)
      print("A cerveja recomendada √©: ", bc)
      print_out = dicRecomendacao["Harmonizacao"][tipo_real]
      print(print_out)
      print_out = dicRecomendacao["Temperatura"][tipo_real]
      print("A temperatura ideal √© entre: %d¬∞C e %d¬∞C" %(print_out[0],print_out[1]))
      #print(ad)
      DataPreco(dia_atual, bc)

if saida == False:
  print("Nao temos recomendacao")

A cerveja recomendada √©:  CORONA EXTRA
PALE LAGER - Hamburger, carnes vermelha e petiscos
A temperatura ideal √© entre: 0¬∞C e 4¬∞C
      Doc. Date  Order qty  ...   Pre√ßo/L  Container Size 2
7669 2020-10-20        2.0  ...  3.087965              8.52
7614 2020-10-16       60.0  ...  2.933358              8.52
7565 2020-10-15       60.0  ...  2.933358              8.52
7395 2020-10-09        1.0  ...  3.518992              8.52
7402 2020-10-09       60.0  ...  3.087965              8.52

[5 rows x 16 columns]
3.0910652649375034