<a href="https://colab.research.google.com/github/joaoleal02/Ambev_iHops/blob/master/ambev_datas_melhorado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [143]:
import pandas as pd
import datetime
empdata = pd.read_csv(r'tabela_ambev_sql_finale.csv',index_col=False, delimiter=';')
dados = empdata.loc[empdata['Postal Code'] == 83630]
print(dados)

        Doc. Date  Order qty  ...   Preço/L  Container Size 2
10     11/01/2021       70.0  ...  2.629129               6.0
11     11/01/2021      140.0  ...  3.775200               6.0
12     11/01/2021      210.0  ...  3.666000               6.0
13     11/01/2021       70.0  ...  3.015600               6.0
14     11/01/2021       70.0  ...  3.733615               6.0
...           ...        ...  ...       ...               ...
21180  11/12/2019       70.0  ...  3.775200               6.0
21181  11/12/2019       70.0  ...  2.629129               6.0
21182  11/12/2019      420.0  ...  2.923183               6.0
21183  11/12/2019      140.0  ...  3.666000               6.0
21184  11/12/2019       70.0  ...  3.015600               6.0

[502 rows x 16 columns]

In [161]:
beer_user = dados.iloc[0]['Subrand']
dados['Doc. Date'] = pd.to_datetime(dados['Doc. Date'], format='%d/%m/%Y')
filtered_df = dados.loc[(dados['Doc. Date'] >= '01/01/2021')]
filtered_df.sort_values("Doc. Date")
print(filtered_df)
print(beer_user)

     Doc. Date  Order qty  PCS delivered  ...        TTC   Preço/L  Container Size 2
10  2021-01-11       70.0           70.0  ...  15.774775  2.629129               6.0
11  2021-01-11      140.0          140.0  ...  22.651200  3.775200               6.0
12  2021-01-11      210.0          210.0  ...  21.996000  3.666000               6.0
13  2021-01-11       70.0           70.0  ...  18.093600  3.015600               6.0
14  2021-01-11       70.0           70.0  ...  22.401691  3.733615               6.0
15  2021-01-11       70.0           70.0  ...  22.774752  3.795792               6.0
185 2021-01-25       70.0           70.0  ...  21.996000  3.666000               6.0
186 2021-01-25       70.0           70.0  ...  18.093600  3.015600               6.0
187 2021-01-25      210.0          210.0  ...  17.539099  2.923183               6.0
188 2021-01-25       70.0           70.0  ...  22.774752  3.795792               6.0
189 2021-01-25       70.0           70.0  ...  22.651200  3.775200               6.0
410 2021-02-08       70.0           70.0  ...  15.774775  2.629129               6.0
411 2021-02-08       70.0           70.0  ...  22.651200  3.775200               6.0
412 2021-02-08       70.0           70.0  ...  16.289683  2.714947               6.0
413 2021-02-08       20.0           20.0  ...  19.099080  3.183180               6.0
414 2021-02-08       70.0           70.0  ...  21.996000  3.666000               6.0
415 2021-02-08      210.0          210.0  ...  17.539099  2.923183               6.0
416 2021-02-08       20.0           20.0  ...  18.673704  3.112284               6.0
417 2021-02-08       70.0           70.0  ...  22.774752  3.795792               6.0
418 2021-02-08       70.0           70.0  ...  22.774752  3.795792               6.0
581 2021-02-22       70.0           70.0  ...  15.774775  2.629129               6.0
582 2021-02-22      140.0          140.0  ...  21.996000  3.666000               6.0
583 2021-02-22      140.0          140.0  ...  18.093600  3.015600               6.0
584 2021-02-22       70.0           70.0  ...  22.401691  3.733615               6.0
585 2021-02-22      140.0          140.0  ...  17.539099  2.923183               6.0
586 2021-02-22       70.0           70.0  ...  22.774752  3.795792               6.0
587 2021-02-22       70.0           70.0  ...  22.774752  3.795792               6.0
588 2021-02-22       70.0           70.0  ...  22.774752  3.795792               6.0

[28 rows x 16 columns]
BUD

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [145]:
from sklearn.cluster import KMeans
import numpy as np

#importando base de dados
df = pd.read_csv("MLiHops.csv")
df

                subrand   ibu  abv (%)  corpo  aroma  tipo
0       BIRRA DEL BORGO  20.0      5.0      1      0    40
1                   BUD  10.0      5.0      0      0     2
2          CAMDEN HELLS  29.0      4.6      0      0     2
3       CAMDEN PALE ALE  39.0      4.0      1      5    40
4          CORONA EXTRA  18.0      4.6      0      0     2
5       GINETTE BLANCHE  12.0      5.0      0      0    41
6        GINETTE BLONDE  29.0      5.0      2      0    40
7         GINETTE FRUIT  12.0      4.0      1      5    20
8         GINETTE LAGER  25.0      4.5      0      0     2
9        GINETTE TRIPLE  15.0      9.0      1     10    44
10                GOOSE  55.0      5.9      1      5    45
11  HOEGARDEN GRAND CRU  35.0      8.5      1      5    46
12       HOEGARDEN ROSE   5.0      3.0      2      5    20
13      HOEGARDEN WHITE  15.0      4.9      0      5    41
14                 KWAK  16.0      8.4      2      5    46
15         LEFFE AMBREE  25.0      6.6      1     15    40
16        LEFFE BLONDE   21.5      6.6      0     15    42
17     LEFFE BLONDE 0,0  10.0      0.0      0     10    42
18          LEFFE BRUNE  20.0      6.5      0     15    43
19      LEFFE LA LEGERE  17.0      5.0      0     15     2
20       LEFFE RITUEL 9  25.0      9.0      2     15    46
21         LEFFE ROYALE  33.0      7.5      1      5    42
22           LEFFE RUBY  10.0      5.0      0      5    20
23         LEFFE TRIPLE  15.0      8.5      1      5    44
24     TRIPLE KARMELIET  31.0      8.4      1     15    44

In [146]:
array1 = []

dicRecomendacao = {

  "Harmonizacao": {
  2 : "AMERICAN PALE ALE - Carnes grelhadas e saladas cítricas",
  40: "PALE LAGER - Hamburger, carnes vermelha e petiscos",
  43: "BROWN ALE - Carnes e petiscos",
  41: "WITBIER - Saladas, frutas do mar e comidas leves",
  44: "TRIPEL - Massas e frutos do mar",
  42: "BLONDE - Petiscos e frutos do mar",
  45: "STRONG - Frutos do mar e massas",
  46: "INDIAN PALE ALE - Queijo, carne vermelha, hamburger e petiscos",
  20: "FRUIT BEER - Sobremesa",
  },
  "Temperatura": {
  2: [8, 12],
  40: [0, 4],
  43: [8, 12],
  41: [4, 7],
  44: [4, 7],
  42: [2, 5],
  45: [10, 12],
  46: [8, 12],
  20: [7, 10],
  }
}

for i in range(25):  #itera sobre os valores e adiciona na lista array1

    temp = []
    temp.clear()

    p1 = df.iloc[i]['ibu']
    temp.append(p1)
    p2 = df.iloc[i]['abv (%)']
    temp.append(p2)
    p3 = df.iloc[i]['corpo']
    temp.append(p3)
    p4 = df.iloc[i]['aroma']
    temp.append(p4)
    p5 = df.iloc[i]['tipo']
    temp.append(p5)
    #p6 = dp.iloc[]["preco"]
    #temp.append(p6)

    array1.append(temp)

X = np.array(array1) #transforma a lista array1 em numpy

print(array1)

[[20.0, 5.0, 1, 0, 40], [10.0, 5.0, 0, 0, 2], [29.0, 4.6, 0, 0, 2], [39.0, 4.0, 1, 5, 40], [18.0, 4.6, 0, 0, 2], [12.0, 5.0, 0, 0, 41], [29.0, 5.0, 2, 0, 40], [12.0, 4.0, 1, 5, 20], [25.0, 4.5, 0, 0, 2], [15.0, 9.0, 1, 10, 44], [55.0, 5.9, 1, 5, 45], [35.0, 8.5, 1, 5, 46], [5.0, 3.0, 2, 5, 20], [15.0, 4.9, 0, 5, 41], [16.0, 8.4, 2, 5, 46], [25.0, 6.6, 1, 15, 40], [21.5, 6.6, 0, 15, 42], [10.0, 0.0, 0, 10, 42], [20.0, 6.5, 0, 15, 43], [17.0, 5.0, 0, 15, 2], [25.0, 9.0, 2, 15, 46], [33.0, 7.5, 1, 5, 42], [10.0, 5.0, 0, 5, 20], [15.0, 8.5, 1, 5, 44], [31.0, 8.4, 1, 15, 44]]

In [147]:
kmeans = KMeans(n_clusters=9, random_state=0).fit(X)
#pega todas a variaveis e as coloca em 10 grupos (mais parecidas)
tips = kmeans.labels_
print(tips)

[4 7 1 8 7 4 8 3 1 0 5 8 3 4 4 2 2 0 2 6 2 8 3 4 2]

In [149]:
def busca(array,beer):
    for i,el in enumerate(array):
        if el==beer:
            return i
    return None
# def DataPreco(data, cerveja):
#   mes = data[3:5]
#   ano = data[7:]
#   dia = data[:1]

#   dados2 = empdata.loc[(empdata['Doc. Date'] == f'{mes}/2021') & (empdata["Subrand"] == "BUD")]
#   print(dados2)
#   return
beer_array = df['subrand'].to_numpy()
tipo_array = df["tipo"].to_numpy()
Y = busca(beer_array, beer_user)
#print(Y)
qlqr = array1[Y]
a = kmeans.predict([qlqr])
#print(a)
var = np.where(tips == a)
print("\n")
#saida da cerveja
bc = ""
cerveja_escolhida = []
print_out = ""
saida = False
dia_atual = "22/02/2021"
#Ultimo dia da tabela

for i in (var):
  for ele in range(len(i)):
    bc = beer_array[i[ele]]
    var_a = i
    var_b = ele
    if bc != beer_user:
      saida = True
      cerveja_escolhida.append(bc)
      ad = i[ele]
      tipo_real = tipo_array[ad]
      #print(tipo_real)
      print("A cerveja recomendada é: ", bc)
      print_out = dicRecomendacao["Harmonizacao"][tipo_real]
      print(print_out)
      print_out = dicRecomendacao["Temperatura"][tipo_real]
      print("A temperatura ideal é entre: %d°C e %d°C" %(print_out[0],print_out[1]))
      #print(ad)
      #DataPreco(dia_atual, bc)

if saida == False:
  print("Nao temos recomendacao")

A cerveja recomendada é:  CORONA EXTRA
AMERICAN PALE ALE - Carnes grelhadas e saladas cítricas
A temperatura ideal é entre: 8°C e 12°C
Empty DataFrame
Columns: [Doc. Date, Order qty, PCS delivered, HL delivered, MACO/HL , Postal Code, Sous groupement, Subrand, Container Type, Unidade Container, Container Size, Latitude, Longitude, TTC, Preço/L, Container Size 2]
Index: []